global:
  scrape_interval: 1m

scrape_configs:
  # https://grafana.com/docs/grafana-cloud/send-data/metrics/metrics-prometheus/prometheus-config-examples/docker-compose-linux/#step-2-create-the-prometheus-configuration-file
  # https://grafana.com/grafana/dashboards/3662-prometheus-2-0-overview/
  # https://grafana.com/grafana/dashboards/3681-prometheus2-0/
  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  # https://grafana.com/grafana/dashboards/1860-node-exporter-full/
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  # https://caddyserver.com/docs/metrics
  # https://grafana.com/grafana/dashboards/14280-caddy-exporter/
  # https://grafana.com/grafana/dashboards/20802-caddy-monitoring/
  # https://github.com/Malfhas/caddy-grafana
  - job_name: caddy
    static_configs:
      # https://stackoverflow.com/a/56910057/310221 -- caddy is not in docker, so use special DNS for local machine
      - targets: ['caddy:2019']

# https://grafana.com/grafana/dashboards/9628-postgresql-database/
# https://grafana.com/grafana/dashboards/9578-alertmanager/

# ? https://grafana.com/docs/grafana/latest/setup-grafana/set-up-grafana-monitoring/#internal-grafana-metrics
